/* 
PAWN INCLUDE
 Kolory 1.0
  by m4tx

Info:
Include zawieraj¹cy zbiór kolorów.
Dziêki temu includowi nie trzeba ju¿ pisaæ definicji kolorów, a przynajmniej tych najwa¿niejszych.

Changelog:
Wersja 1.0 [aktualna]:
- Pierwsze wydanie
- 90 kolorów
*/

/* Reklama
www.my-nokia.c0.pl - forum o Nokiach
www.quake-forum.c0.pl - forum o serii gier Quake
www.my-comics.c0.pl - Portal z komiksami
*/

#if defined _kolory_included
	#endinput
#endif

#define _kolory_included

#define COLOR_BLACK 			0x00000000
#define COLOR_BROWN 			0x8F4747FF
#define COLOR_GREY 				0xAFAFAFAA
#define COLOR_WHITE				0xFFFFFFAA
#define COLOR_BLUE 				0x0000BBAA
#define COLOR_GREEN 			0x33AA33AA
#define COLOR_YELLOW 			0xFFFF00AA
#define COLOR_YELLOW2 			0xF5DEB3AA
#define COLOR_RED 				0xAA3333AA
#define COLOR_ORANGE 			0xFF9900AA
#define COLOR_PINK 				0xFF66FFAA
#define COLOR_PURPLE 			0xC2A2DAAA
#define COLOR_VIOLET			0x9955DEEE
#define COLOR_LEMON 			0xDDDD2357

#define COLOR_GRAD 				0xAAAAAAFF
#define COLOR_GRAD1 			0xB4B5B7FF
#define COLOR_GRAD2 			0xBFC0C2FF
#define COLOR_GRAD3 			0xCBCCCEFF
#define COLOR_GRAD4 			0xD8D8D8FF
#define COLOR_GRAD5 			0xE3E3E3FF
#define COLOR_GRAD6 			0xF0F0F0FF

#define COLOR_FADE1 			0xE6E6E6E6
#define COLOR_FADE2 			0xC8C8C8C8
#define COLOR_FADE3 			0xAAAAAAAA
#define COLOR_FADE4 			0x8C8C8C8C
#define COLOR_FADE5 			0x6E6E6E6E

#define COLOR_LIGHTYELLOW 		0xFAEAA9FF
#define COLOR_LIGHTORANGE 		0xF7A26FFF
#define COLOR_LIGHTNEUTRALBLUE 	0xabcdef66
#define COLOR_LIGHTBLUE 		0x33CCFFAA
#define COLOR_LIGHTCYAN 		0xAAFFCC33
#define COLOR_LIGHTBLUEGREEN 	0x0FFDD349
#define COLOR_LIGHTRED 			0xFF99AADD
#define COLOR_LIGHTGREEN 		0x24FF0AB9
#define COLOR_LIGHTPINK 		0xFF80FFFF

#define COLOR_DARKGREEN 		0x12900BBF
#define COLOR_DARKBLUE 			0x300FFAAB
#define COLOR_DARKRED 			0x660000AA
#define COLOR_DARKBROWN 		0x530000FF
#define COLOR_DARKVIOLET 		0x400040FF
#define COLOR_DARKYELLOW 		0x808000FF
#define COLOR_DARKPINK 			0x400040FF
#define COLOR_DARKGREY 			0x808080FF

#define COLOR_SEAGREEN 			0x00EEADDF
#define COLOR_GrayWHITE 		0xEEEEFFC4
#define COLOR_GREENISHGOLD 		0xDEAD4370
#define COLOR_NEUTRALBLUE 		0xABCDEF01
#define COLOR_NEUTRALGREEN 		0x81CFAB00
#define COLOR_BLUEGREEN 		0x46BBAA00
#define COLOR_NEUTRAL 			0xABCDEF97
#define COLOR_MEDIUMBLUE 		0x63AFF00A

#define COLOR_PINKER 			0xFF0080FF
#define COLOR_PANICRED 			0xFF0000FF

#define COLOR_RUDY 				0xDF7000FF

#define TEAM_GROVE_COLOR 		0x00D900C8
#define TEAM_VAGOS_COLOR 		0xFFC801C8
#define TEAM_BALLAS_COLOR 		0xD900D3C8
#define TEAM_AZTECAS_COLOR 		0x01FCFFC8
#define TEAM_CYAN_COLOR 		0xFF8282AA
#define TEAM_ORANGE_COLOR 		0xFF830000
#define TEAM_COR_COLOR 			0x39393900
#define TEAM_BAR_COLOR 			0x00D90000
#define TEAM_TAT_COLOR 			0xBDCB9200
#define TEAM_CUN_COLOR 			0xD900D300
#define TEAM_STR_COLOR 			0x01FCFF00
#define TEAM_ADMIN_COLOR 		0x00808000
#define TEAM_GREEN_COLOR 		0xFFFFFFAA
#define TEAM_JOB_COLOR 			0xFFB6C1AA
#define TEAM_HIT_COLOR 			0xF3E198FF
#define TEAM_BLUE_COLOR 		0x8D8DFF00

#define BEZOWY 					0xFFFFADAA
#define BIALY					0xFFFFFFAA
#define BLEKITNY 				0x33CCFFAA
#define BORDOWY 				0x99001FAA
#define BRAZOWY 				0x997A00AA
#define CIEMNY_ZIELONY 			0x336633AA
#define CZARNY 					0x000000AA
#define CZERWONY 				0xFF0000AA
#define FIOLETOWY 				0x9E3DFFAA
#define NIEBIESKI 				0x0000FFAA
#define POMARANCZOWY 			0xFF8000AA
#define ROZOWY 					0xFF66CCAA
#define SZARY 					0xB0B0B0AA
#define ZIELONY 				0x00CC00AA
#define ZOLTY 					0xFFFF00AA

#define ADMINFS_MESSAGE_COLOR 	0xFF444499
#define PM_INCOMING_COLOR     	0xFFFF22AA
#define PM_OUTGOING_COLOR     	0xFFCC2299
#define COLOR_ADMIN 			0xFF0000AA
#define CWARN 					0xFF4444FF