AntiDeAMX();
new KtoJestOnline[MAX_PLAYERS];
new IloscGraczy = 0;
new PojazdySerwera[MAX_VEH];
new IloscPojazdow = 0;
new testzabez[MAX_PLAYERS];
new qr = 0;
new MozeBycWPojezdzie[MAX_PLAYERS];
new SprawdzaniePojazdu[MAX_PLAYERS];
new TimerSprawdzaniaPojazdu[MAX_PLAYERS];
new Relog[MAX_PLAYERS];
new AntyCheatWizualizacja[MAX_PLAYERS];
new AntyCheatWizualizacjaTimer[MAX_PLAYERS];
new WlaczNadajKare[MAX_PLAYERS];
new UzylLPM[MAX_PLAYERS];
new UzylLPMTimer[MAX_PLAYERS];
new ogmx = 0;
new Float:LastSpeed[MAX_PLAYERS][3];
new Bar:KartyGracza111[MAX_PLAYERS];
new Bar:KartyGracza222[MAX_PLAYERS];
new ALK[MAX_PLAYERS];
new Bar:KartyGracza333[MAX_PLAYERS];
new Bar:KartyGracza444[MAX_PLAYERS];
new Bar:KartyGracza555[MAX_PLAYERS];
new Bar:KartyGracza666[MAX_PLAYERS];
new WybralMozliwoscPoker[MAX_PLAYERS];
new MaPilke[MAX_PLAYERS];
new PosiadaPilke[MAX_OBIEKT];
new StatusPilki[MAX_OBIEKT];
new spawns[MAX_PLAYERS];
new Text: LosSantosFM;
new Text: Worek;
new Frezowany[MAX_PLAYERS];
new AB[MAX_PLAYERS];
new ABTimer[MAX_PLAYERS];
new SkinIDM[MAX_PLAYERS],SkinIDW[MAX_PLAYERS];
new	bool: GangZonePL[MAX_PLAYERS];
new Text:Telefon[16];
new Text3D:Vopis[MAX_VEH];
new SNINFO = 0;
new SpawnPlayerRandom[MAX_PLAYERS];
new AntySpam[MAX_PLAYERS][50];
new	AFK[MAX_PLAYERS];
new AntyCheatBroni[MAX_PLAYERS];
new PosiadanaBron[MAX_PLAYERS];
new TimerAntyCheat[MAX_PLAYERS];
new Tag[MAX_PLAYERS];
new impreza;
new	DzwoniID[MAX_PLAYERS];
new Dzwoni[MAX_PLAYERS];
new Odebral[MAX_PLAYERS];
new dzwon[MAX_PLAYERS];
new MozeBanowac[MAX_PLAYERS];
new Wedkuje[MAX_PLAYERS];
new Dostal[MAX_PLAYERS];
new MalowanieKolor[MAX_PLAYERS][4];
new Rolki[MAX_PLAYERS];
new spanuje[MAX_PLAYERS];
new FrezzPlayer[MAX_PLAYERS];
new OpisekJaki[MAX_PLAYERS];
new AFKTimer;
new AIR[MAX_PLAYERS];
new Pracuje[MAX_PLAYERS];
new UzywaBudkiUID[MAX_PLAYERS];
new LOCKW[MAX_PLAYERS];
new Bieg[MAX_PLAYERS];
new reload = 0;
new Text3D:NapisWyszedl[MAX_PLAYERS];
new bool:obiektinedit[MAX_OBIEKT];
new SpecUruchomiony[MAX_PLAYERS],
		SpecCel[MAX_PLAYERS];
new Text:Light;
new Float:createdareax[MAX_PLAYERS];
new Float:animacja[MAX_PLAYERS];
new Float:createdareay[MAX_PLAYERS];
new edycjaobiektow[MAX_PLAYERS];
new Wylogowany[MAX_PLAYERS];
new ACOFF[MAX_VEH] = 0;
new Float:createdareah[MAX_PLAYERS];
new Float:createdareaxx[MAX_PLAYERS];
new Float:createdareayy[MAX_PLAYERS];
new Float:createdareahh[MAX_PLAYERS];
new Float:createddoor[MAX_PLAYERS];
new PJ[MAX_PLAYERS];
new bool:flying[MAX_PLAYERS];
new Text: OBJ[MAX_PLAYERS];
new Text3D:Opisek[MAX_PLAYERS];
new DutyAdmina[MAX_PLAYERS];
new DutyDZ[MAX_PLAYERS];
new NaprawiaID[MAX_PLAYERS],
	NaprawiaVeh[MAX_PLAYERS],
	NaprawiaIUID[MAX_PLAYERS],
	NaprawianieCena[MAX_PLAYERS],
	NaprawianieDUID[MAX_PLAYERS],
	GPS[MAX_PLAYERS],
	PASY[MAX_PLAYERS],
	NaprawianieVW[MAX_PLAYERS],
	NaprawiaCzas[MAX_PLAYERS],
	LakierujeCzas[MAX_PLAYERS],
	NaprawiaODL[MAX_PLAYERS];
new DutyNR[MAX_PLAYERS];
new PoziomLakieru[MAX_PLAYERS];
new RoznicaLakieru[MAX_PLAYERS];
new Rekawiczki[MAX_PLAYERS];
new Nieznajomy[MAX_PLAYERS];
new Text:TextNaDrzwi[MAX_PLAYERS];
new PlayerText:TextOferty0[MAX_PLAYERS];
new PlayerText:TextOferty1[MAX_PLAYERS];
new PlayerText:TextOferty2[MAX_PLAYERS];
new PlayerText:TextOferty3[MAX_PLAYERS];
new PlayerText:TextOferty4[MAX_PLAYERS];
new PlayerText:TextOferty5[MAX_PLAYERS];
new PlayerText:TextOferty6[MAX_PLAYERS];
new PlayerText:TextOferty7[MAX_PLAYERS];
new PlayerText:Lokalizacja[MAX_PLAYERS];
new Amfeta[MAX_PLAYERS];
new Kokaina[MAX_PLAYERS];
new Extasa[MAX_PLAYERS];
new LSD[MAX_PLAYERS];
new Grzyby[MAX_PLAYERS];
new Hera[MAX_PLAYERS];
new Mefedron[MAX_PLAYERS];
new WpisalKase[MAX_PLAYERS];
new GraWPokera[MAX_PLAYERS];
new PasekGloduWLACZONY[MAX_PLAYERS];
new OstrzezeniaAir[MAX_PLAYERS];
//new OstrzezeniaAirs[MAX_PLAYERS];
new Discman[MAX_PLAYERS];
new PlayerText:WylosowaneKarty[MAX_PLAYERS];
new PlayerText:WylosowaneKarty1[MAX_PLAYERS];
new PlayerText:WylosowaneKarty2[MAX_PLAYERS];
new PlayerText:WylosowaneKarty3[MAX_PLAYERS];
new PlayerText:WylosowaneKarty4[MAX_PLAYERS];
new PlayerText:WylosowaneKarty5[MAX_PLAYERS];
new PlayerText:KartyGracza[MAX_PLAYERS];
new PlayerText:KartyGracza1[MAX_PLAYERS];
new PlayerText:KartyGracza2[MAX_PLAYERS];
new PlayerText:KartyGracza3[MAX_PLAYERS];
new PlayerText:KartyGracza4[MAX_PLAYERS];
new PlayerText:KartyGracza5[MAX_PLAYERS];
new PlayerText:KartyGracza6[MAX_PLAYERS];
new PlayerText:KartyGracza11[MAX_PLAYERS];
new PlayerText:KartyGracza22[MAX_PLAYERS];
new PlayerText:KartyGracza33[MAX_PLAYERS];
new PlayerText:KartyGracza44[MAX_PLAYERS];
new PlayerText:KartyGracza55[MAX_PLAYERS];
new PlayerText:KartyGracza66[MAX_PLAYERS];
new PlayerText:Poker1[MAX_PLAYERS];
new PlayerText:Poker2[MAX_PLAYERS];
new PlayerText:Poker3[MAX_PLAYERS];
new PlayerText:Poker4[MAX_PLAYERS];
new PlayerText:Poker5[MAX_PLAYERS];
new PlayerText:Poker6[MAX_PLAYERS];
new PlayerText:KartaGracza1[MAX_PLAYERS];
new PlayerText:KartaGracza2[MAX_PLAYERS];
new PlayerText:KartaGracza3[MAX_PLAYERS];
new PlayerText:KartaGracza4[MAX_PLAYERS];
new PlayerText:KartaGracza5[MAX_PLAYERS];
new PlayerText:KartaGracza6[MAX_PLAYERS];
new PlayerText:KartaGracza7[MAX_PLAYERS];
new PlayerText:KartaGracza8[MAX_PLAYERS];
new PlayerText:KartaGracza9[MAX_PLAYERS];
new PlayerText:KartaGracza10[MAX_PLAYERS];
new PlayerText:KartaGracza11[MAX_PLAYERS];
new PlayerText:KartaGracza12[MAX_PLAYERS];
new PlayerText:KartaGracza13[MAX_PLAYERS];
new PlayerText:KartaGracza14[MAX_PLAYERS];
new taxijedz[MAX_PLAYERS];
new karnet[MAX_PLAYERS];
new silka[MAX_PLAYERS];
new wyciskanie[MAX_PLAYERS];
new podnoszenie[MAX_PLAYERS];
new sek[MAX_PLAYERS];
new Text: Wyscig[MAX_PLAYERS];
new CzasWyswietlaniaTextuNaDrzwiach[MAX_PLAYERS];
new TrasaDuty[MAX_PLAYERS];
new TrasaDutyNr[MAX_PLAYERS];
new Xkara = 0;
new BUSS[MAX_PLAYERS];
new Edytors[MAX_PLAYERS];
new OferujeA[MAX_PLAYERS];
new bool:zalogowany[MAX_PLAYERS];
new PRZEBYTE[MAX_PLAYERS];
new Proby[MAX_PLAYERS];
new OstatnieDrzwi[MAX_PLAYERS];
new Float:dHP[MAX_PLAYERS];
new Text:Textdrawodkar;
new Float:ACHP;
new Text:brudny;
new Text:Licznik[MAX_PLAYERS];
new	bool:dBron[MAX_PLAYERS][47], dAmmo[MAX_PLAYERS][47];
new	ACtekst_global[150];
//new , ACBron, ACAmmo
new Float:dOstatniX[MAX_PLAYERS],
	Float:dOstatniY[MAX_PLAYERS],
	Float:dOstatniZ[MAX_PLAYERS],
	Float:dDystans;